import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Tab from "./lib/components/tab";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="tabs is-medium">
          <ul>
            <Tab href="/lecturers">Lecturers</Tab>
            <Tab href="/lecturers/add">Add</Tab>
          </ul>
        </div>
        <div className="p-5">
          {children}
        </div>
      </body>
    </html>
  );
}
